from .base_specification import WanLatentEncodeProcessor, WanModelSpecification
from .control_specification import WanControlModelSpecification
from .reference_specification import WanReferenceModelSpecification
